# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-07 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='date_for_scripting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_Date_Roll', models.DateField()),
                ('end_Date_Roll', models.DateField()),
                ('start_Date_Delta', models.DateField()),
                ('end_Date_Delta', models.DateField()),
            ],
            options={
                'db_table': 'date_for_scripting',
            },
        ),
    ]
