# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-16 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_db_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_user_details',
            name='phone',
            field=models.IntegerField(default=9876543210),
        ),
    ]
