# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_db_user_details_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ry_start', models.DateField(null=True)),
                ('ry_end', models.DateField(null=True)),
                ('ryd_start', models.DateField(null=True)),
                ('ryd_end', models.DateField(null=True)),
                ('cr_start', models.DateField(null=True)),
                ('cr_end', models.DateField(null=True)),
                ('crd_start', models.DateField(null=True)),
                ('crd_end', models.DateField(null=True)),
                ('cr_quarter', models.CharField(max_length=50)),
                ('pre_quarter', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'app_config',
            },
        ),
    ]
