# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-13 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_appconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='db_user_details',
            new_name='db_user_details1',
        ),
        migrations.AlterModelTable(
            name='db_user_details1',
            table='user_details1',
        ),
    ]
