# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0005_auto_20181213_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_user_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(default=9876543210)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.RemoveField(
            model_name='db_user_details1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='db_user_details1',
            name='phone',
        ),
    ]
