# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-13 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0006_auto_20181213_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='db_user_details1',
        ),
    ]
